explode:
  dialogue:
    why:
      - "[ Чому? ]"
      - "[ Мені треба ще й прибиратися кожен раз. ]"
      - "[ Воу... серйозно?]"
      - "[  ]"
      -
    sixninefourtwo: найс 👍
    nineninenineninenine: |
      [ Це достатньо. Як ви `#####` змогли цього навіть досягти!? Ви що, не розумієте скільки всесвітів ви знищили? . ]

      ⚠️ увага: ви абсолютно мерзенні.
  info: "Кількість розбитих вами Сонць: {amount, pretty_num}"
  YouKilledNiko: "[ Ви вбили Ніко. ]"
