explode:
  dialogue:
    why:
      - "[ Зачем? ]"
      - "[ Мне всё время приходится прибирать осколки, когда так делают. ]"
      - "[ Ого... Серьёзно что ли? ]"
      - "[  ]"
      -
    sixninefourtwo: найс 👍
    nineninenineninenine: |
      [ Хватит. Как ты, '#####', вообще достиг(ла) ТАКОГО числа?! Ты хоть знаешь, сколько миров было уничтожено? ]

      ⚠️ предупреждение: Это ПРОСТО омерзительно.
  info: "Солнце было расколото {amount, pretty_num} раз"
  YouKilledNiko: "[ Вы убили Нико. ]"
