_metadata:
  name: сокровища
  description: Отобразить сокровища из вашего (или чужого!) инвентаря
minis:
  tips:
    where_to_get_treasure: "вы можете получить больше сокровищ торговлей в магазине или отправкой Никоготчи на поиски таковых!"
    public: "вы можете использовать {/inventory/treasures} с аргументом «public: True» чтобы показать свои сокровища в чате!"
loading: "[ {loading, emoji} Загрузка {target_type, select, current {ваших} other {чужих}} сокровищ... ]"
empty: "[ У {user_id, user, mention} нет ни одного сокровища ]"
message: |
  ### сокровища {user}
  {treasures}
