_metadata:
  name: inventory
  description: Commands related to the player's inventory
options:
  target-user:
    name: target
    description: "Person the inventory of which to check instead"

item_entry_template: "**`{spacer}{amount, pretty_num}`** {icon} {name}"
