_metadata:
  name: sun
  description: All things to do with Suns
give:
  _metadata:
    name: give
    description: Give someone a sun!
explode:
  _metadata:
    name: explode
    description: 💥💥💥💥💥💥💥💥💥
  dialogue:
    why:
      - "[ Why? ]"
      - "[ I have to clean up everytime someone does this. ]"
      - "[ Wow… really? ]"
      - "[  ]"
      -

    sixninefourtwo: nice 👍
    nineninenineninenine: |
      [ That's enough. How the `####` did you manage to reach this number!? Do you understand how many worlds you have destroyed? ]

      ⚠️ warning: Utterly despicable.

  info: "Shatter count: {amount, pretty_num}"
  YouKilledNiko: "[ You killed Niko. ]"
