_metadata:
  # weblate-flags: max-length:32, ignore-same
  name: sun
  # weblate-flags: max-length:100
  description: All things to do with Suns
give:
  _metadata:
    # weblate-flags: max-length:32, ignore-same
    name: give
    # weblate-flags: max-length:100
    description: Give someone a sun!
  cooldown: "[ They've already received a sun from someone today! You'll be able to give them one {unable_until, time, relative} ]"
  self: "[ {doer, user, mention} did a flip with the sun {sun, emoji} in their hands!! ]"
  message: "[ {giver, user, mention} gave {receiver, user, mention} a sun!! ]"
explode:
  _metadata:
    name: explode
    description: 💥💥💥💥💥💥💥💥💥
  dialogue:
    why:
      - "[ Why? ]"
      - "[ I have to clean up everytime someone does this. ]"
      - "[ Wow… really? ]"
      - "[  ]"
      -

    sixninefourtwo: nice 👍
    nineninenineninenine: |
      [ That's enough. How the `####` did you manage to reach this number!? Do you understand how many worlds you have destroyed? ]

      ⚠️ warning: Utterly despicable.

  info: "Shatter count: {amount, pretty_num}"
  YouKilledNiko: "[ You killed Niko. ]"
