_metadata:
  name: treasures
  description: View the treasures you have in your inventory (or see someone else's!)
minis:
  tips:
    public: "you can use {/inventory/treasures} with `public: True`, to show off your treasures in chat!"
    where_to_get_treasure: you can get more treasure by trading in the shop or sending Nikogotchis to find some!
loading: "[ {loading, emoji} Loading {target_type, select, current {your} other {their}} treasures… ]"
empty: "[ {user_id, user, mention} doesn't have any treasure ]"
message: >
  ### {user}'s treasures

  {treasures}
